### PR TITLE
Without the https links the demo page doesn't work

### PR DESCRIPTION
**Pull request by MrCsabaToth**
Looks ugly and not functional. The fix is simple.

### CODE REVIEW

**Comment by faulknercs** [comment]
Thanks for contribution!

**Comment by MrCsabaToth** [comment]
No problem. Exact same thing happened with chardin.js's demo page. I wonder if it's about maybe OSX + Safari? Because I don't have Mac, so I can imagine that maybe. I know I could try Safari though. What OS platform and browser did you test the demo page? I'm just really curious, since same was going on with chardin.

**Comment by faulknercs** [comment]
I'm using Firefox/Win 7, but I always opened demo page through http. So https version wasn't tested.

**Comment by MrCsabaToth** [comment]
Actually, I didn't test that case (when the main page is http, and now the CDN links are https). For me even if I try to view the demo page as http, I get redirected to https automatically.

**Pull request merged**
